default:
	echo "Specify a branch"

test-one:
	@g++ -std=c++20 -o part-one.out part-one.cpp 
	@./part-one.out test-input.txt
	@rm part-one.out

run-one:
	@g++ -std=c++20 -o part-one.out part-one.cpp 
	@./part-one.out real-input.txt
	@rm part-one.out

test-two:
	@g++ -std=c++20 -o part-two.out part-two.cpp 
	@./part-two.out test-input.txt
	@rm part-two.out

run-two:
	@g++ -std=c++20 -o part-two.out part-two.cpp 
	@./part-two.out real-input.txt
	@rm part-two.out